//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 

namespace SOAPService
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GetCityServiceasmxSoap", Namespace = "http://tempuri.org/")]
    public partial class GetCityServiceasmx : System.Web.Services.Protocols.SoapHttpClientProtocol {

        private System.Threading.SendOrPostCallback GetCityAndIdOperationCompleted;

        /// <remarks/>
        public GetCityServiceasmx() {
            this.Url = "http://localhost:55057/GetCityServiceasmx.asmx";
        }

        /// <remarks/>
        public event GetCityAndIdCompletedEventHandler GetCityAndIdCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCityAndId", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CITYLIST[] GetCityAndId() {
            object[] results = this.Invoke("GetCityAndId", new object[0]);
            return ((CITYLIST[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetCityAndId(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCityAndId", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public CITYLIST[] EndGetCityAndId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CITYLIST[])(results[0]));
        }

        /// <remarks/>
        public void GetCityAndIdAsync() {
            this.GetCityAndIdAsync(null);
        }

        /// <remarks/>
        public void GetCityAndIdAsync(object userState) {
            if ((this.GetCityAndIdOperationCompleted == null)) {
                this.GetCityAndIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityAndIdOperationCompleted);
            }
            this.InvokeAsync("GetCityAndId", new object[0], this.GetCityAndIdOperationCompleted, userState);
        }

        private void OnGetCityAndIdOperationCompleted(object arg) {
            if ((this.GetCityAndIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityAndIdCompleted(this, new GetCityAndIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }

        internal object GetCityId()
        {
            throw new NotImplementedException();
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class CITYLIST {

        private long idField;

        private System.Nullable<long> city_IDField;

        private string city_NameField;

        private string countryField;

        private System.Nullable<long> latField;

        private System.Nullable<long> lonField;

        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<long> City_ID {
            get {
                return this.city_IDField;
            }
            set {
                this.city_IDField = value;
            }
        }

        /// <remarks/>
        public string City_Name {
            get {
                return this.city_NameField;
            }
            set {
                this.city_NameField = value;
            }
        }

        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<long> Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<long> Lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void GetCityAndIdCompletedEventHandler(object sender, GetCityAndIdCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityAndIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal GetCityAndIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public CITYLIST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CITYLIST[])(this.results[0]));
            }
        }
    }
}