//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CITYLISTDBEntities : DbContext
    {
        public CITYLISTDBEntities()
            : base("name=CITYLISTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITYLIST> CITYLISTs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    
        public virtual ObjectResult<SP_GET_CITY_Result> SP_GET_CITY(string cITY_NAME)
        {
            var cITY_NAMEParameter = cITY_NAME != null ?
                new ObjectParameter("CITY_NAME", cITY_NAME) :
                new ObjectParameter("CITY_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_CITY_Result>("SP_GET_CITY", cITY_NAMEParameter);
        }
    
        public virtual ObjectResult<SP_ALL_ID_AND_CITYNAME_Result> SP_ALL_ID_AND_CITYNAME()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ALL_ID_AND_CITYNAME_Result>("SP_ALL_ID_AND_CITYNAME");
        }
    
        public virtual ObjectResult<SP_GET_CITY_NAME_Result> SP_GET_CITY_NAME(Nullable<long> cITY_ID)
        {
            var cITY_IDParameter = cITY_ID.HasValue ?
                new ObjectParameter("CITY_ID", cITY_ID) :
                new ObjectParameter("CITY_ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_CITY_NAME_Result>("SP_GET_CITY_NAME", cITY_IDParameter);
        }
    }
}
